server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/derrick1314/pwc-config.git
          username: derrick1314
          password: Thisismy123!